"""initial schema

Revision ID: ec85c9059503
Revises: 
Create Date: 2026-06-28 16:28:50.246532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec85c9059503'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('coin', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('coin', 'source', 'content_hash')
    )
    op.create_index('idx_content_coin_source_id', 'content_items', ['coin', 'source', 'source_id'], unique=False)
    op.create_index('idx_content_coin_source_timestamp', 'content_items', ['coin', 'source', 'timestamp'], unique=False)
    op.create_table('prices',
    sa.Column('coin', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('coin', 'timestamp')
    )
    op.create_table('signals',
    sa.Column('coin', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('coin', 'timestamp', 'signal_name')
    )
    op.create_index('idx_signals_coin_signal_timestamp', 'signals', ['coin', 'signal_name', 'timestamp'], unique=False)
    op.create_table('sentiment',
    sa.Column('coin', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('analyzer', sa.String(), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['coin', 'source', 'content_hash'], ['content_items.coin', 'content_items.source', 'content_items.content_hash'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coin', 'source', 'content_hash', 'analyzer')
    )
    op.create_index('idx_sentiment_coin_analyzer_source', 'sentiment', ['coin', 'analyzer', 'source', 'content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sentiment_coin_analyzer_source', table_name='sentiment')
    op.drop_table('sentiment')
    op.drop_index('idx_signals_coin_signal_timestamp', table_name='signals')
    op.drop_table('signals')
    op.drop_table('prices')
    op.drop_index('idx_content_coin_source_timestamp', table_name='content_items')
    op.drop_index('idx_content_coin_source_id', table_name='content_items')
    op.drop_table('content_items')
    # ### end Alembic commands ###
